name: Linux Build

on:
  workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  #SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: configure
      run: ./configure
      
    - name: Setup premake
      uses: abel0b/setup-premake@v1
      
    - name: Run Premake
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: premake5 gmake2

    - name: make
      run: make config=${{env.BUILD_CONFIGURATION}}
      
    - uses: actions/upload-artifact@v2
      with:
        name: lunar-artifact
        path: |
          game/
          
    - uses: actions/upload-artifact@v2
      with:
        name: lunar-artifact
        path: |
          bin/${{env.BUILD_CONFIGURATION}}/*
